#Import
import time

#varibles
a = "XXX"
loop = 30
lemur = "bob"
a = ""
skip = ""
food = 0
play = 0
clean = 0
#lemurstore
def lem():
    time.sleep(3)
    space()
    global a
    global food, play, clean
    global lemur
    a = input("Do you feed (a) play (b) or clean (c)")
    if a == "a":
        print("How much food do you give the lemur? To keep a healthy diet, lemurs need 50 food make sure to give a good amount. It is okay if you give a little too much. Or a little too less")
        food = int(input("Enter lemur food amount"))
        if food >= 60:
            print("Your lemur is too fat.")
        elif food <= 45:
            print("Your lemur is too skinny")
        else:
            print("You gave your lemur a good amount! Great job!")
        lem()
    elif a == "b":
        print("Time for play! Type how much play you wan't your lemur to have. Lemurs require more than 40 play each day")
        play = int(input("Enter lemur play amount"))
        if play <= 40:
            print("Your lemur has depression")
        else:
            print("Your lemur had good play! Good job!")
        lem()
    elif a == "c":
        print("Your lemur HATES being dirty. Make sure to give them a good clean. Your lemur likes 30 clean but no more than 75 clean, or your lemur will get sticky.")
        clean = int(input("Enter lemur clean amount"))
        if clean <= 25:
            print("The lemur isn't clean enough, it's angry and it scratches you")
        elif clean >= 75:
            print("Your lemur is too sticky. It shoves you away angrily")
        lem()
        
def lemname():
    global lemur
    print("So, what will you name your lemur")
    lemur = input("INSERT GOOD LEMUR NAME: ")
    print("...")
    time.sleep(3)
    print("Wow! The name {} really seems good with that lemur".format(lemur))    
    time.sleep(2)
    print("Lets have some fun!")
    lem()

#Function  
def space():
   
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")

#ImQuinn
print("A GAME BY ImQuinn")
time.sleep(2.5)
space()
skip = input("Do you want to skip the main story, and head to the lemur store? ")
if skip == "yes":
    lemname()
else:
    print("Okay! Starting now...")
    time.sleep(2)
    space()
# begining
time.sleep(1)
print("It was a stormy night")
time.sleep(2.5)
print("You left evrything")
time.sleep(2.5)
print("It was a long journey")
time.sleep(2.5)
print("And you forgot your passport")
time.sleep(2.5)
print("You came to the border")
time.sleep(2.5)
print("You")
time.sleep(1)
print("real")
time.sleep(1)
print("ize")
time.sleep(2.5)
print("You cry and ask to be let in")
time.sleep(2.5)
print("The gaurds start to get angry")
time.sleep(2.5)
print("You")
time.sleep(1)
print("sneak")
time.sleep(1)
print("in")
time.sleep(2.5)
print("The gaurds notice")
time.sleep(1)
print("Your")
time.sleep(1)
print("getting")
time.sleep(1)
print("caught")
time.sleep(2.5)
print("You scream as hard as you can")
time.sleep(1)
print("The")
time.sleep(1)
print("rain")
time.sleep(1)
print("falls")
space()
print("*PHONE VIBRATES*")
time.sleep(5)
print("Sorry, the caller has not been found please press one to try again, ple-")
print("*HANGS UP*")
print("CALL ENDED")
print("I wasted my calling time on this?!?")
print("The lawyer's nuber doesn't even exist!!!")
print("It's been over a week, and i'm still here.")
print("I need to escape!")
print("Lets get this party started...")
space()
print("LOADING: Part One: Getting to the admin center")
time.sleep(3)
space()
print("Ok, lets get started")


#main
def main1():
    print("==========")
    print("Part one")
    print("==========")
    time.sleep(3)
    a = input("Should i go through the vent (a), or steal a guards keycard (b)?")
    if a == "a":
        print("Im kinda claustrophobic, but whatever")
        print("Oh no! The wall are closing in! AAAH AAAH AAAH")
        print("Better luck next time!")
        main1()
    else:
        print("Hmm i need a distaction...")
        print("HEY BILL, DO THE CRAB DANCE TO THAT GAURD OVER THERE!!!")
        print("*intense crab dancing*")
        print("YES! I snatched it.")
        print("Okay, lets head through my cell blocks mains door.")
        print("Okay i snucked in")
        a = input("Should i go down the east (a), or west corridor (b)")
        if a == "a":
            print("Hmmm... it looks like this is the way to the admin center")
            print("Okay lets go through here")
            print("Wait... are those gaurds coming for me?!?!?")
            a = input("Should i go in the closet (a), or sneak into the vents (b)")
            if a == "a":
                print("Okay wait, why is there a toilet in this closet?")
                print("Wait this is a bathroom.")
                print("There is knocking at the door.")
                print("The gaurds needed to go")
                main1()
            else:
                print("Okay! Im in the vents, again.")
                print("Uhhh UUHhhh UUUHHHHHH I CAN'T TAKE IT!")
                print("THIS IS SO SCARY")
                print("but i have too...")
                print("Uhh what way should i go?")
                a = input("Should i go left (a) or right (b)?")
                if a == "a":
                    print("The air seems to be rushing this way")
                    print("Wow this is geting strong")
                    print("AAAH! IT'S PULLING ME IN!")
                    print("IS THAT A HUGE FAN?!?!?")
                    print("The blades wanted sushi, so they turned you into some")
                    main1()
                else:
                    print("Okay the vent seems to be getting bigger!")
                    print("There is a sign here")
                    print("IT SAYS ADMIN CENTER!")
        else:
            print("Hmmm... do i see dogs?")
            print("OOOH! Those are gaurd dogs")
            print("Wait ehy are they coming for me???")
            print("Oh, i forgot that im escap-")
            print("AAAH!")
            print("The dogs thought you were a dog treat, sorry")
            main1()

main1()

print("Yay! I made it!")
time.sleep(1)
print("Lets get out of this!")
time.sleep(1)
print("It looks like IT'S PARTY TIME")
time.sleep(1)
print("Time to bust out the ice cream!")
time.sleep(1)
print("WOOHOO!")
time.sleep(1)
print("*Party music plays*")
time.sleep(2.5)
print("Wait... are those guards?")
time.sleep(1)
space()
print("LOADING: Part Two: The Chase")
time.sleep(3)
space()
print("When you came to the border, you noticed somthing suspicious")
time.sleep(2.5)
print("There was a huge building behind it")
time.sleep(2.5)
print("You later realize that it is the CYBERMAX")
time.sleep(2.5)
print("That wasn't the only thing suspicous")
time.sleep(2.5)
print("You")
time.sleep(1)
print("noticed")
time.sleep(1)
print("flames")
time.sleep(1)
print("you")
time.sleep(1)
print("saw")
time.sleep(1)
print("people")
time.sleep(5)
print("they we're escaping, though")
time.sleep(5)
space()
print("I'm running")
time.sleep(2)
print("I guess im like those people escaping")
time.sleep(2)
print("Lets get going")
time.sleep(2)
a = input("Should i run (a), or run towards the guards (b)?")
if a == "a":
    print("I AM SO FAST")
    print("Now i'm a bit slower")
    print("And slower")
    print("AAH! IM COUGHT!")
    print("You walk at the speed of a grandma, but the gaurds are a bit faster")
    space()
    print("You have to go all the way back to your cell.")
    print("Bye!")
    main1()
else:
    print("Ok here it goes!")
    print("Getting close")
    print("SMASH!")
    print("Yes! I knocked them over, and now i have a tazer (:")
    print("You will have the option to taze in some scenes!")
    space()
    print("Part 2 - and a half")
    time.sleep(5)
    space()
    print("Okay! Looks like there are more gaurds coming!")
a = input("Should i attack (a), or taze (b)")
if a == "a":
    print("I ATTACK!")
    print("But my arms are getting tired")
    print("And more tired")
    print("Your arms are as strong as a grandma, but the gaurds are stronger.")
    print("Back to your cell!")
    main1()
else:
    print("You press the trigger")
    print("*tazer noise*")
    print("That was easy")
    print("And oh! The exit is right here!")
space()
print("LOADING: Part Three: City Life")
time.sleep(5)
space()
print("Wow! That tazer sure was handy!")
time.sleep(2)
print("Okay, looks like im on 20th street")
time.sleep(2)
print("I heard that there is a lemur store on 5th street! I really need a lemur...")
time.sleep(2)
print("WHY IS THIS CAR BLOCKING MY PATH!?!")
time.sleep(2)
print("*tazes car*")
time.sleep(2)
print("Oooh a gaming dumpster!")
time.sleep(2)
print("(in the cyberverse they have gaming dumpsters, if you really needed to game, but you didn't have something to play on nearby)")
time.sleep(5)
space()
print("Hello! Welcome to the gaming dumpster!")
time.sleep(2)
print("Uhhh, hi?")
time.sleep(2)
print("PLAY VIDEOGAME NOW")
time.sleep(2)
print("Uhh, sure ok!")
time.sleep(2)
print("You slowly start to sleep while gaming")
time.sleep(2)
print("Your crazy day is really getting to you.")
time.sleep(2)
print("Goodnight!")
time.sleep(2)
space()
print("Uhh whats going on")
time.sleep(2)
print("Your wake up in the back of a police car")
time.sleep(2)
print("Your right next to the couthouse")
time.sleep(2)
print("You")
time.sleep(1)
print("feel")
time.sleep(1)
print("handcuffs")
time.sleep(2)
print("Wait what is that store over there?")
time.sleep(2)
print("You")
time.sleep(1)
print("see")
time.sleep(1)
print("lemurs")
time.sleep(2)
print("OMG!")
time.sleep(0.5)
print("OMG!")
time.sleep(0.5)
print("OMG!")
time.sleep(0.5)
print("I'TS A LEMUR")
time.sleep(0.5)
print("You try your hardest to kick the door")
time.sleep(2)
print("It won't budge")
time.sleep(2)
print("A police officer finnaly comes")
time.sleep(2)
print("They open the door")
time.sleep(2)
print("You run the fastest you ever have before")
time.sleep(2)
print("You finnaly arrive and pet a lemur")
time.sleep(2)
print("It bites you")
time.sleep(2)
print("You scream")
time.sleep(2)
print("The gaurd catches up")
time.sleep(2)
space()
print("You wake up in a jail cell")
time.sleep(2)
print("The plan failed")
time.sleep(2)
space()
print("THE END")
time.sleep(1)
print("Or is it?")
time.sleep(2)
space()
print("After serving your time, you finnaly get to the lemur store")
time.sleep(3)
lemname()

#season 2
def s2():
    space()
    print("LOADING: Season 2")
    time.sleep(3)
    space()
    time.sleep(2.5)
    print("Why hello there.")
    time.sleep(2.5)
    print("I have been waiting so long to see you")
    time.sleep(2.5)
    print("It's nice meeting new people, isn't it?")
    time.sleep(2.5)
    print("Expecially when i get to control there life")
    time.sleep(2.5)
    print("It is my mission to make sure you never escape this prison")
    time.sleep(2.5)
    print("Oh, and that lemur of yours has been taken far, far, far away from here")
    time.sleep(2.5)
    print("Have fun")
    time.sleep(2.5)
    print("All")
    time.sleep(1)
    print("a")
    time.sleep(1)
    print("lone")
    time.sleep(2.5)
    print("Enjoy your stay in solitary confinement")
    time.sleep(2.5)
    print("Goodbye")
    time.sleep(2.5)
    space()
    print("A GAME BY ImQuinn")
    time.sleep(2.5)
    print("Escape To THe Cyberverse: Season 2")
    time.sleep(2.5)
    space()
    print("You are sent to the most secure cell in the world")
    time.sleep(2.5)
    print("You spend 24/7 in a tiny room")
    time.sleep(2.5)
    print("You have 5 security cameras monitoring you at all times")
    time.sleep(2.5)
    print("Outside your cell is over 10 locked doors")
    time.sleep(2.5)
    print("And over 100 security cameras outside your cell")
    time.sleep(2.5)
    print("Every wall has 6 inches of titanium and then 10 feet of concrete")
    time.sleep(2.5)
    print("You only have a toilet, and a sink")
    time.sleep(2.5)
    print("You don'r have a bed")
    time.sleep(2.5)
    print("You are in here for the rest of you life")
    time.sleep(2.5)
    print("This will be hard")
    time.sleep(2.5)
    space()
    print()
    print("YOu notice that all you get to eat is a loaf of bread, and some water")
    time.sleep(2.5)
    print("You start to go insane, how boring it is")
    time.sleep(2.5)
    print("By the 5th day, you have had enough")
    time.sleep(2.5)
    print("Time for escape")
    time.sleep(2.5)
    space()